version: '3'

tasks:
  default:
    cmds:
      - task: help

  help:
    desc: List tasks
    cmds:
      - task -l

  build:
    desc: Build CLI to bin/pea
    cmds:
      - mkdir -p bin
      - go build -o bin/pea .

  run:
    desc: Run the app with optional args
    cmds:
      - go run . {{.CLI_ARGS}}

  fmt:
    desc: Format source files
    cmds:
      - go fmt ./...

  vet:
    desc: Vet code for issues
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  tidy:
    desc: Tidy module dependencies
    cmds:
      - go mod tidy

  test:
    desc: Run tests
    cmds:
      - go test ./...

  e2e:
    desc: Run end-to-end tests
    cmds:
      - go test -v ./e2e

  check:
    desc: Run fmt, vet, lint, and test
    cmds:
      - task fmt
      - task vet
      - task lint
      - task test

  ci:
    desc: Run CI-equivalent checks (build, lint, test)
    cmds:
      - go build ./...
      - golangci-lint run ./...
      - go test ./...
